export const TOGGLE_CATEGORY = 'TOGGLE_CATEGORY';
export const START_FETCH_CATEGORIES = 'START_FETCH_CATEGORIES';
export const SUCCESS_FETCH_CATEGORIES = 'SUCCESS_FETCH_CATEGORIES';
export const START_FETCH_ITEMS = 'START_FETCH_ITEMS';
export const SUCCESS_FETCH_ITEMS = 'SUCCESS_FETCH_ITEMS';
export const FETCH_ADDITIONAL_ITEMS_SUCCESS = 'FETCH_ADDITIONAL_ITEMS_SUCCESS';
