export const ADD_CARS = 'ADD_CARS';
export const ADD_CARS_ERROR = 'ADD_CARS_ERROR';
export const TOGGLE_CATEGORY = 'TOGGLE_CATEGORY';
export const START_FETCH_CATEGORIES = 'START_FETCH_CATEGORIES';
export const SUCCESS_FETCH_CATEGORIES = 'SUCCESS_FETCH_CATEGORIES';
